"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThemeConfig = exports.SuggestionConfig = exports.PollConfig = exports.GiveawayConfig = void 0;
var GiveawayConfig_1 = require("./GiveawayConfig");
Object.defineProperty(exports, "GiveawayConfig", { enumerable: true, get: function () { return GiveawayConfig_1.GiveawayConfig; } });
var PollConfig_1 = require("./PollConfig");
Object.defineProperty(exports, "PollConfig", { enumerable: true, get: function () { return PollConfig_1.PollConfig; } });
var SuggestionConfig_1 = require("./SuggestionConfig");
Object.defineProperty(exports, "SuggestionConfig", { enumerable: true, get: function () { return SuggestionConfig_1.SuggestionConfig; } });
var ThemeConfig_1 = require("./ThemeConfig");
Object.defineProperty(exports, "ThemeConfig", { enumerable: true, get: function () { return ThemeConfig_1.ThemeConfig; } });
